export const ADD_POST = 'ADD_POST';

export const VIEW_POST_START = 'VIEW_POST_START';
export const VIEW_POST_SUCCESS = 'VIEW_POST_SUCCESS';
export const VIEW_POST_FAIL = 'VIEW_POST_FAIL';

export const VIEW_SELECTED_POST_START = 'VIEW_SELECTED_POST_START';
export const VIEW_SELECTED_POST_SUCCESS = 'VIEW_SELECTED_POST_SUCCESS';
export const VIEW_SELECTED_POST_FAIL = 'VIEW_SELECTED_POST_FAIL';

export const IS_AUTH = 'IS_AUTH';
export const IS_NOTAUTH = 'IS_NOTAUTH';


export const ADD_BLOG_START = 'ADD_BLOG_START';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_FAIL = 'ADD_BLOG_FAIL';

export const VIEW_BLOG_START = 'VIEW_BLOG_START';
export const VIEW_BLOG_SUCCESS = 'VIEW_BLOG_SUCCESS';
export const VIEW_BLOG_FAIL = 'VIEW_BLOG_FAIL';

export const VIEW_SELECTED_BLOG_START = 'VIEW_SELECTED_BLOG_START';
export const VIEW_SELECTED_BLOG_SUCCESS = 'VIEW_SELECTED_BLOG_SUCCESS';
export const VIEW_SELECTED_BLOG_FAIL = 'VIEW_SELECTED_BLOG_FAIL';
export const VIEW_SELECTED_BLOG_DELETE = 'VIEW_SELECTED_BLOG_DELETE';

export const DELETED = 'DELETED';
export const UPDATED_SUCESS = 'UPDATED_SUCESS';
